<a href="https://colab.research.google.com/github/sfreagin/Quantum-Programming/blob/main/Jones_calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stephen Reagin
## PHYS 208 - Homework #4
An important application of the quarter-wave plate is its use in an “isolator”. For example, to prevent feedback from interferometers into lasers by front-surface, back reflections. Two common forms of isolators are a “Faraday Isolator” based on Faraday rotation, and a “Pseudo-Isolator” based on polarizers and waveplates. The latter is considerably less expensive, but only functions properly when certain assumptions are met. In this homework you will design both type of isolators.
#### 1. **Faraday Isolator**
Design a device that transmits light traveling through it in one direction, but blocks the light traveling in the other direction. Assume the input light is horizontally polarized and the output polarization should also be horizontal. Prove that this design has the desired behavior by using Jones calculus.

In [ ]:
import numpy as np

### Setting up the Jones matrices for each apparatus the light will encounter

In [ ]:
HP = np.array([[1,0],[0,0]])                    #horizontal linear polarizer
HWP = np.array([[1,-1],[-1,-1]]) / np.sqrt(2)   #half-wave plate with theta = 22.5 degrees
Faraday = np.array([[1,1],[-1,1]]) / np.sqrt(2) #Faraday rotator with theta = 45 degrees
Mirror = np.array([[-1,0],[0,1]])               #mirror
E_in = np.array([[1],[1]])                      #input E_x and E_y (not normalized, not sure it matters)

#### A. Sending light through the forward direction
#### B. Interacting with a mirror and sending light in the backwards direction

In [ ]:
step1 = np.matmul(HP,E_in)
step2 = np.matmul(Faraday, step1)
step3 = np.matmul(HWP, step2)
step4 = np.matmul(HP, step3)
step5 = np.matmul(Mirror, step4)
step6 = np.matmul(HP, step5)
step7 = np.matmul(HWP, step6)
step8 = np.matmul(Faraday, step7)

step9 = np.matmul(HP, step8)

steps_state = {1: step1, 2: step2, 3: step3,
               4: step4, 5: step5, 6: step6,
               7: step7, 8: step8, 9: step9,}

steps_name = {1: "Horizontal Polarizer",
              2: "Faraday Rotator",
              3: "Half-Wave Plate",
              4: "Horizontal Polarizer",
              5: "Mirror",
              6: "Horizontal Polarizer",
              7: "Half-Wave Plate",
              8: "Faraday Rotator",
              9: "Horizontal Polarizer"}


for i in range(1,5):
  print(f"Polarization after step {i}, applying {steps_name[i]}: \n{np.round(steps_state[i],4)}\n")

print("************************\nNow we interact with a mirror \
and travel in reverse order\n***********************\n")

for i in range(5,10):
  print(f"Polarization after step {i}, applying {steps_name[i]}: \n{np.round(steps_state[i],4)}\n")

Polarization after step 1, applying Horizontal Polarizer: 
[[1]
 [0]]

Polarization after step 2, applying Faraday Rotator: 
[[ 0.7071]
 [-0.7071]]

Polarization after step 3, applying Half-Wave Plate: 
[[ 1.]
 [-0.]]

Polarization after step 4, applying Horizontal Polarizer: 
[[1.]
 [0.]]

************************
Now we interact with a mirror and travel in reverse order
***********************

Polarization after step 5, applying Mirror: 
[[-1.]
 [ 0.]]

Polarization after step 6, applying Horizontal Polarizer: 
[[-1.]
 [ 0.]]

Polarization after step 7, applying Half-Wave Plate: 
[[-0.7071]
 [ 0.7071]]

Polarization after step 8, applying Faraday Rotator: 
[[0.]
 [1.]]

Polarization after step 9, applying Horizontal Polarizer: 
[[0.]
 [0.]]



The state after passing through the device (but before the mirror) is horizontally polarized as expected, $\begin{bmatrix} E_{x} \\ 0 \end{bmatrix} = E_{x}\begin{bmatrix} 1 \\ 0 \end{bmatrix} $

The state after reflection and traveling back through the device is $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$, that is to say, no light is passed (light is blocked)

### 2. **Pseudo-Isolator**
Design a device that transmits light in one direction and blocks the light that is retro-reflected back into the device without using a Faraday rotator. If the input polarization is linear horizontal, what is the output polarization state of the light? Will this device still function as intended if the retro-reflected light has its polarization changed by some downstream optical element? Prove this device has the expected behavior using Jones calculus.

In [ ]:
#need two more Jones matrices here
rotate_basis = np.array([[1,-1],[1,1]]) / np.sqrt(2)  #rotate the basis by 45 degrees, transpose is the inverse
QWP = np.array([[1,0],[0,1j]])                        #Quarter wave plate

In [ ]:
step1 = np.matmul(HP, E_in)
step2 = np.matmul(rotate_basis, step1)
step3 = np.matmul(QWP, step2)
step4 = np.matmul(rotate_basis.T, step3)
step5 = np.matmul(Mirror, step4)
step6 = np.matmul(rotate_basis.T, step5)
step7 = np.matmul(QWP, step6)
step8 = np.matmul(rotate_basis, step7)
step9 = np.matmul(HP, step8)

steps_state = {1: step1, 2: step2, 3: step3,
               4: step4, 5: step5, 6: step6,
               7: step7, 8: step8, 9: step9,}

steps_name = {1: "Horizontal Polarizer",
              2: "Rotate Basis",
              3: "Quarter-Wave Plate",
              4: "Rotate Basis (inverse)",
              5: "Mirror",
              6: "Rotate Basis (inverse)",
              7: "Half-Wave Plate",
              8: "Rotate Basis",
              9: "Horizontal Polarizer"}

for i in range(1,5):
  print(f"Polarization after step {i}, applying {steps_name[i]}: \n{np.round(steps_state[i],4)}\n")

print("************************\nNow we interact with a mirror \
and travel in reverse order\n***********************\n")

for i in range(5,10):
  print(f"Polarization after step {i}, applying {steps_name[i]}: \n{np.round(steps_state[i],4)}\n")

Polarization after step 1, applying Horizontal Polarizer: 
[[1]
 [0]]

Polarization after step 2, applying Rotate Basis: 
[[0.7071]
 [0.7071]]

Polarization after step 3, applying Quarter-Wave Plate: 
[[0.7071+0.j    ]
 [0.    +0.7071j]]

Polarization after step 4, applying Rotate Basis (inverse): 
[[ 0.5+0.5j]
 [-0.5+0.5j]]

************************
Now we interact with a mirror and travel in reverse order
***********************

Polarization after step 5, applying Mirror: 
[[-0.5-0.5j]
 [-0.5+0.5j]]

Polarization after step 6, applying Rotate Basis (inverse): 
[[-0.7071+0.j    ]
 [ 0.    +0.7071j]]

Polarization after step 7, applying Half-Wave Plate: 
[[-0.7071+0.j]
 [-0.7071+0.j]]

Polarization after step 8, applying Rotate Basis: 
[[ 0.+0.j]
 [-1.+0.j]]

Polarization after step 9, applying Horizontal Polarizer: 
[[0.+0.j]
 [0.+0.j]]



The state after passing through the device (but before the mirror) is polarized as $\frac{E_{x}}{2}\begin{bmatrix} 1+i \\ i-1 \end{bmatrix} $

The state after reflection and traveling back through the device is $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$, that is to say, no light is passed (light is blocked)